

services:
  server:
    container_name: todo_server
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      # - /app/node_modules
    # environment:
      # - NODE_ENV=production
